### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by PaulDebus** [peterkovesi/ImageProjectiveGeometry.jl#20]
Hey,

thanks for including my "recent" pull requests. It fixed some bugs that bugged me in my work. Now that I would like to publish my package, I would ask you to create a new release that includes those changes, so I can easily depend on your package as it is. 

Thanks and regards!

**Comment by peterkovesi** [comment]
Done. Hopefully tagbot will do its bit and get this version registered

**Comment by PaulDebus** [comment]
Thanks! Now we have to wait for the registry apparently :+1:
