### ISSUE TITLE
[Feature Request] Add Sensor Size to the Camera Struct

### ISSUE THREAD

**Issue by PaulDebus** [peterkovesi/ImageProjectiveGeometry.jl#21]
Hey,

I continue to use your library and have a good time doing this. Now, I want to compute the resolution an image will have on a plane, given the camera struct and the distance to that plane. I use the size of the physical sensor for this using 

```julia
sensor_element = cam.cols / sensor_size_x
resolution = sensor_element / cam.fx * distance
```
This made me think if including the sensor size in the `Camera` struct as an additional field would generally be valuable.

If you agree, I can make a pull request for this, this could maybe be used in different functions as well. The `imagecorners2plane` function comes to mind, which could have been useful here but still is a little mystical to me. Or do I miss a point in the implementation and the sensor size is actually not required?

Thanks for your time!

**Comment by peterkovesi** [comment]
The sensor size is not really required.  As you point out you can achieve what you want with `imagecorners2plane()`. 

Note that specifying two adjacent image points defines two viewing rays.   These can be projected to your plane using `imagept2plane()`.  The separation of the rays at the points where they intersect your plane is the resolution .  The sensor size or element size is not required to compute these rays.

In your expression above `sensor_element / cam.fx` basically represents the angle between viewing rays of adjacent pixels.
When you multiply this by `distance` you get your resolution


```

**Comment by PaulDebus** [comment]
Thanks for the feedback. Using `imagept2plane` sounds even more suitable for that task. 

Am I correct in assuming, that you specify the focal length in pixels? I normally have them in mm or something, so I would have to convert it to pixels, using the size of one pixel on the sensor as the conversion factor?

**Comment by peterkovesi** [comment]
Yes, the focal length is in pixels.  If you want a physical size then you can scale things by the sensor element size.

**Comment by PaulDebus** [comment]
Thanks, this makes a lot of sense and many of my calculations much easier.
