### ISSUE TITLE
Call to `size` seems to have incorrect parameters

### ISSUE THREAD

**Issue by nlw0** [peterkovesi/ImageProjectiveGeometry.jl#25]
This should probably be just `size(x1)`, not sure this is a version conflict or what.

https://github.com/peterkovesi/ImageProjectiveGeometry.jl/blob/018afdd34ae571a62d832733c70bf808d8a0ebb0/src/projective.jl#L1338

**Comment by peterkovesi** [comment]
Sorry I am unable to review this issue because I am on a 3 week hike with
very little phone reception! By all means make a PR as I am sure there are
some rough edges in the code. I will try to get back to you as soon as I
get some reasonable connectivity.

**Comment by peterkovesi** [comment]
Thank you for finding that error.  I need to improve my test coverage by quite a bit! I have finally fixed it and tagged a new version.
