### ISSUE TITLE
where is the doc pages url? 

### ISSUE THREAD

**Issue by zsz00** [peterkovesi/ImageProjectiveGeometry.jl#28]

**Comment by peterkovesi** [comment]
The documentation is provided as a set of markdown files available from README.md.  Scroll down to the Function Reference section. There you will find links to all the functions grouped by the titles 'projective', 'cornerfeatures', ransac etc etc.
At the time I originally developed the package Documenter.jl was not available, or was in its infancy, hence the basic markdown format of the documentation.
Please not also that I am afraid I have not been very active in maintaining this code to match changes in the Images ecosystem. There will be some functions that will not work.  Please file any issues as you find them and I will try to attend to them.
