### ISSUE TITLE
Removing PyPlot dependency

### ISSUE THREAD

**Issue by nlw0** [peterkovesi/ImageProjectiveGeometry.jl#36]
Despite the amazing work that has been done integrating Julia with Python and Matplotlib, it is unfortunately a tricky thing to get it to work. Automatic installation is just not reliable. And as noted in the Readme, this can be greatly inconvenient. I would propose to remove the dependency on `PyPlot`. I can prepare a patch, but it would be great to have some directions about what to do with the existing code that depends on it. Some "demo" code might simply not be included in the module, what I think it's already the case for some of the files, but some functions have plotting features deep inside them, at it'll be hard to refactor that out. Can I simply go on removing any plotting code from these cases?

I have these changes in my fork, I didn't want to make a PR before having a talk. https://github.com/nlw0/ImageProjectiveGeometry.jl

**Comment by peterkovesi** [comment]
You are most welcome to make a PR.  However there may be a case for some plotting to remain using some other plotting library in some cases, we can discuss this with your PR

It would be good to remove the dependency of PyPlot as I agree that it can be troublesome.  The presence of PyPlot in the code is somewhat historical.  I started developing the code back when Julia was at 0.5 - 0.6 and the plotting options were a bit limited.  It the time PyPlot was one of the few that offered full 3D plotting and also the ability to overlay plots over images, and Matplotlib was mature.  Things have changed now.

Note also that I am retired and now find myself not writing any code there days.  My maintenance of these repositories is minimal at best.

**Comment by nlw0** [comment]
Ok, I created #37 . I completely understand having plotting mixed with the code... And I only started using Julia because matplotlib integration was so good!
